<?php

$finder = (new PhpCsFixer\Finder())
    ->in([
        __DIR__ . '/src',
        __DIR__ . '/tests'
    ])
    ->exclude([
        'autogenerated_content',
        'tests/fixtures',
    ])
    ->notPath([
        'dump.php',
        'src/exception_file.php',
    ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@PhpCsFixer' => true,
    ])
    ->setFinder($finder)
    ;